version: '3'

services:
  storeDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
    - storedbdata:/var/lib/mysql
    networks:
      - storemynet
  storeDBMigration:
    image: storedbmigration
    environment:
      - STORE_DATABASE_URL=storeDB
    depends_on:
      storeDB:
        condition: service_healthy
    networks:
      - storemynet
  storeowner:
    image: storeowner
    environment:
      - STORE_DATABASE_URL=storeDB
    depends_on:
      - storeDBMigration
    ports:
    - 5003:5002
    networks:
      - storemynet
  storecourier:
    image: storecourier
    environment:
      - STORE_DATABASE_URL=storeDB
    depends_on:
      - storeDBMigration
    ports:
      - 5004:5002
    networks:
      - storemynet
  storecustomer:
    image: storecustomer
    environment:
      - STORE_DATABASE_URL=storeDB
    depends_on:
      - storeDBMigration
    ports:
      - 5005:5002
    networks:
      - storemynet
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - storemynet
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8082:8080
      - 7077:7077
    networks:
      - storemynet
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8083:8081
    networks:
      - storemynet
    environment:
      - SPARK_MASTER=spark://spark-master:7077
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8084:8081
    networks:
      - storemynet
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  storespark:
    image: storespark
    environment:
      - PRODUCTION=True
      - SOCKET_IP=0.0.0.0
      - SOCKET_PORT=9090
      - SPARKAPP_IP=storespark
      - DATABASE_IP=storeDB
    ports:
      - 5006:5002
    networks:
      - storemynet



volumes:
  storedbdata:

networks:
  storemynet: